name = "OWENSFEA"
uuid = "5906b1e7-6737-4278-91ec-d653c88addb4"
authors = ["Kevin R. Moore <kevmoor@sandia.gov> and contributors"]
version = "1.0.0"

[deps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FLOWMath = "6cb5d3fb-0fe8-4cc2-bd89-9fe0b19a99d3"
GXBeam = "974624c9-1acb-4ad6-a627-8ac40fc27a3e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
MAT = "0.10"
DelimitedFiles = "1"
ArnoldiMethod = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
